/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
// @ts-ignore
import { ApiSuccessResponseListGetBookmarkListResponse } from '../../src/model';
// @ts-ignore
import { ApiSuccessResponseobject } from '../../src/model';
/**
 * BookmarkControllerApi - axios parameter creator
 * @export
 */
export const BookmarkControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary createBookmark
         * @param {number} feedId feedId
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBookmarkUsingPOST: async (feedId: number, userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'feedId' is not null or undefined
            assertParamExists('createBookmarkUsingPOST', 'feedId', feedId)
            const localVarPath = `/api/bookmark/{feedId}`
                .replace(`{${"feedId"}}`, encodeURIComponent(String(feedId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary deleteBookmark
         * @param {number} feedId feedId
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBookmarkUsingDELETE: async (feedId: number, userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'feedId' is not null or undefined
            assertParamExists('deleteBookmarkUsingDELETE', 'feedId', feedId)
            const localVarPath = `/api/bookmark/{feedId}`
                .replace(`{${"feedId"}}`, encodeURIComponent(String(feedId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getBookmarkList
         * @param {number} page page
         * @param {number} [pageSize] pageSize
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBookmarkListUsingGET: async (page: number, pageSize?: number, userId?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getBookmarkListUsingGET', 'page', page)
            const localVarPath = `/api/bookmark`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BookmarkControllerApi - functional programming interface
 * @export
 */
export const BookmarkControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BookmarkControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary createBookmark
         * @param {number} feedId feedId
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBookmarkUsingPOST(feedId: number, userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSuccessResponseobject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBookmarkUsingPOST(feedId, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary deleteBookmark
         * @param {number} feedId feedId
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBookmarkUsingDELETE(feedId: number, userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSuccessResponseobject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBookmarkUsingDELETE(feedId, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary getBookmarkList
         * @param {number} page page
         * @param {number} [pageSize] pageSize
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBookmarkListUsingGET(page: number, pageSize?: number, userId?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSuccessResponseListGetBookmarkListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBookmarkListUsingGET(page, pageSize, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BookmarkControllerApi - factory interface
 * @export
 */
export const BookmarkControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BookmarkControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary createBookmark
         * @param {number} feedId feedId
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBookmarkUsingPOST(feedId: number, userId?: number, options?: any): AxiosPromise<ApiSuccessResponseobject> {
            return localVarFp.createBookmarkUsingPOST(feedId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary deleteBookmark
         * @param {number} feedId feedId
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBookmarkUsingDELETE(feedId: number, userId?: number, options?: any): AxiosPromise<ApiSuccessResponseobject> {
            return localVarFp.deleteBookmarkUsingDELETE(feedId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getBookmarkList
         * @param {number} page page
         * @param {number} [pageSize] pageSize
         * @param {number} [userId] userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBookmarkListUsingGET(page: number, pageSize?: number, userId?: number, options?: any): AxiosPromise<ApiSuccessResponseListGetBookmarkListResponse> {
            return localVarFp.getBookmarkListUsingGET(page, pageSize, userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BookmarkControllerApi - object-oriented interface
 * @export
 * @class BookmarkControllerApi
 * @extends {BaseAPI}
 */
export class BookmarkControllerApi extends BaseAPI {
    /**
     * 
     * @summary createBookmark
     * @param {number} feedId feedId
     * @param {number} [userId] userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookmarkControllerApi
     */
    public createBookmarkUsingPOST(feedId: number, userId?: number, options?: AxiosRequestConfig) {
        return BookmarkControllerApiFp(this.configuration).createBookmarkUsingPOST(feedId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary deleteBookmark
     * @param {number} feedId feedId
     * @param {number} [userId] userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookmarkControllerApi
     */
    public deleteBookmarkUsingDELETE(feedId: number, userId?: number, options?: AxiosRequestConfig) {
        return BookmarkControllerApiFp(this.configuration).deleteBookmarkUsingDELETE(feedId, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary getBookmarkList
     * @param {number} page page
     * @param {number} [pageSize] pageSize
     * @param {number} [userId] userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BookmarkControllerApi
     */
    public getBookmarkListUsingGET(page: number, pageSize?: number, userId?: number, options?: AxiosRequestConfig) {
        return BookmarkControllerApiFp(this.configuration).getBookmarkListUsingGET(page, pageSize, userId, options).then((request) => request(this.axios, this.basePath));
    }
}
