/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../../base';
// @ts-ignore
import { ApiSuccessResponseobject } from '../../src/model';
// @ts-ignore
import { OauthKakaoSignInRequest } from '../../src/model';
/**
 * OauthControllerApi - axios parameter creator
 * @export
 */
export const OauthControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary oauthKakaoSignIn
         * @param {OauthKakaoSignInRequest} request request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthKakaoSignInUsingPOST: async (request: OauthKakaoSignInRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('oauthKakaoSignInUsingPOST', 'request', request)
            const localVarPath = `/api/oauth/kakao/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OauthControllerApi - functional programming interface
 * @export
 */
export const OauthControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OauthControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary oauthKakaoSignIn
         * @param {OauthKakaoSignInRequest} request request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async oauthKakaoSignInUsingPOST(request: OauthKakaoSignInRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiSuccessResponseobject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.oauthKakaoSignInUsingPOST(request, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * OauthControllerApi - factory interface
 * @export
 */
export const OauthControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OauthControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary oauthKakaoSignIn
         * @param {OauthKakaoSignInRequest} request request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        oauthKakaoSignInUsingPOST(request: OauthKakaoSignInRequest, options?: any): AxiosPromise<ApiSuccessResponseobject> {
            return localVarFp.oauthKakaoSignInUsingPOST(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OauthControllerApi - object-oriented interface
 * @export
 * @class OauthControllerApi
 * @extends {BaseAPI}
 */
export class OauthControllerApi extends BaseAPI {
    /**
     * 
     * @summary oauthKakaoSignIn
     * @param {OauthKakaoSignInRequest} request request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OauthControllerApi
     */
    public oauthKakaoSignInUsingPOST(request: OauthKakaoSignInRequest, options?: AxiosRequestConfig) {
        return OauthControllerApiFp(this.configuration).oauthKakaoSignInUsingPOST(request, options).then((request) => request(this.axios, this.basePath));
    }
}
