/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetNicknameSearchResponse } from './get-nickname-search-response';

/**
 * 
 * @export
 * @interface ApiSuccessResponseListGetNicknameSearchResponse
 */
export interface ApiSuccessResponseListGetNicknameSearchResponse {
    /**
     * 
     * @type {Array<GetNicknameSearchResponse>}
     * @memberof ApiSuccessResponseListGetNicknameSearchResponse
     */
    'data'?: Array<GetNicknameSearchResponse>;
}

