/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeedResponse
 */
export interface FeedResponse {
    /**
     * 
     * @type {string}
     * @memberof FeedResponse
     */
    'authorNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedResponse
     */
    'authorProfileImageUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeedResponse
     */
    'bookMarked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedResponse
     */
    'feedId'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof FeedResponse
     */
    'hashtags'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FeedResponse
     */
    'imageUrls'?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof FeedResponse
     */
    'liked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedResponse
     */
    'modifiedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedResponse
     */
    'numberOfLike'?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedResponse
     */
    'numberOfReply'?: number;
}

