/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FollowResponse
 */
export interface FollowResponse {
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FollowResponse
     */
    'following'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'modifiedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'profileImageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'signupType'?: FollowResponseSignupTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof FollowResponse
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof FollowResponse
     */
    'username'?: string;
}

export const FollowResponseSignupTypeEnum = {
    Email: 'EMAIL',
    KakaoTalk: 'KAKAO_TALK'
} as const;

export type FollowResponseSignupTypeEnum = typeof FollowResponseSignupTypeEnum[keyof typeof FollowResponseSignupTypeEnum];


