/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetNicknameSearchResponse
 */
export interface GetNicknameSearchResponse {
    /**
     * 
     * @type {string}
     * @memberof GetNicknameSearchResponse
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetNicknameSearchResponse
     */
    'profileImageUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetNicknameSearchResponse
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetNicknameSearchResponse
     */
    'username'?: string;
}

