/* tslint:disable */
/* eslint-disable */
/**
 * 개발자취 - ArtBubble
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReplyResponse
 */
export interface ReplyResponse {
    /**
     * 
     * @type {string}
     * @memberof ReplyResponse
     */
    'authorNickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReplyResponse
     */
    'authorProfileImageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReplyResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReplyResponse
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReplyResponse
     */
    'feedId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReplyResponse
     */
    'modifiedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReplyResponse
     */
    'numberOfRereply'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReplyResponse
     */
    'replyId'?: number;
}

