import { Icon } from "@chakra-ui/react";
import { faHouse } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <span>Next.js 시작</span>
        <Icon
          as={FontAwesomeIcon}
          icon={faHouse}
          color="blue.700"
          boxSize={50}
        />
      </main>
    </>
  );
}
